### ISSUE TITLE
To Codelife.com Checklist

### ISSUE THREAD

**Issue by alexandersimoes** [Datawheel/codelife#128]
Here's a list of things before we go live:

- [x] Get HTTPs configured
- [x] Get @jhmullen configured to SSH into server
- [ ] Enable traditional text pw logins for SSH while we're in brazil (less secure but will work on any comp)
- [x] Update callback URLs for social media logins to point to codelife.com
- [x] Google Analytics
- [x] Test sharing on facebook, twitter etc
- [x] Check entire site in 1400px width display
- [x] Back-up local copy of DB
