### ISSUE TITLE
create new homepage

### ISSUE THREAD

**Issue by davelandry** [Datawheel/codelife#222]
Logged out version should show:
- [x] video
- [x] tagline
- [x] login/signup

Logged in version should show:
- [x] current in-progress island (#229)
- [x] welcome message

All versions should show:
- [x] featured projects (#223 and #227)
- [x] featured codeblocks (#224 and #228)

**Comment by jhmullen** [comment]
Added a reference to the current island for dave to retrieve.  Access this by hitting `/api/userprogress/` and accessing `.current` of the returned payload.

**Comment by davelandry** [comment]
@jhmullen so... #229 is done?
